### ISSUE TITLE
Can't easily override repos in settings

### ISSUE THREAD

**Issue by invernizzie** [andyceo/ansible-role-git#2]
Hi! Thanks for building this, it's proving useful to me.

However, I can't find a way of overriding only [the `repositories` map in the default settings](https://github.com/andyceo/ansible-role-git/blob/master/defaults/main.yml#L34) without losing the rest of the defaults. How do you use this yourself?

**Comment by andyceo** [comment]
Hello!

Thank you for using this!

If we use `hash_behaviour = merge` (like there: https://github.com/andyceo/ansible-example/blob/master/ansible.cfg#L2), we can not disable working with default values in https://github.com/andyceo/ansible-role-git/blob/master/defaults/main.yml#L34 because your new and default hashes will be merged together, and the only way to disable them is to redefine them with some dummy repos.

Of course this is very wrong. I completely removed default values of `repositories`, so end user will not face with this trouble. Now default value of `repositories` is an empty hash.
